### ISSUE TITLE
Create Knight Valid Moves (+ Tests)

### ISSUE THREAD

**Issue by GeroStoewe** [AlexInABox/chess-g4#16]

**Comment by AlexInABox** [comment]
sicher dass es in #18 #14 nicht genau darum geht?

**Comment by GeroStoewe** [comment]
Ich habe für das Pferd die spezifischen Moves und Tests ausschließlich für die Bewegungen des Pferds geschrieben. Ich dachte, dass #18 und #14 etwas allgemeiner sind und nicht so spezifisch.
